# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SkopjePulse' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SkopjePulse  
  pod 'lottie-ios'
  pod 'RealmSwift'

  target 'SkopjePulseTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
