# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SkopjePulse' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SkopjePulse
  pod 'Device', '~> 3.2.1'
  pod 'lottie-ios'

  target 'SkopjePulseTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
